services:
  db:
    image: postgres:16
    environment: { POSTGRES_DB: app, POSTGRES_USER: app, POSTGRES_PASSWORD: app }
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  redis: { image: redis:7, ports: ["6379:6379"] }
  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server /data --console-address ":9001"
    environment: { MINIO_ROOT_USER: minio, MINIO_ROOT_PASSWORD: minio123 }
    ports: ["9000:9000","9001:9001"]
    volumes: ["minio:/data"]
  search:
    image: opensearchproject/opensearch:2.15.0
    environment: { discovery.type: single-node, OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m, OPENSEARCH_INITIAL_ADMIN_PASSWORD: Admin123! }
    ulimits: { memlock: { soft: -1, hard: -1 } }
    ports: ["9200:9200","9600:9600"]
  mailhog: { image: mailhog/mailhog, ports: ["8025:8025","1025:1025"] }
  api:
    build: ../../apps/api
    env_file: [../../apps/api/.env.dev]
    depends_on: [db,redis,minio,search,mailhog]
    ports: ["8000:8000"]
    volumes: [../../apps/api:/app]
  web:
    build: ../../apps/frontend
    env_file: [../../apps/frontend/.env.dev]
    depends_on: [api]
    ports: ["3000:3000"]
    volumes: [../../apps/frontend:/app]
volumes: { pgdata: {}, minio: {} }
