from typing import Protocol, Dict, Any, List
class SafetyPack(Protocol):
    def score_content(self, *, text: str, meta: Dict[str, Any]) -> Dict[str, Any]: ...
    def user_reputation(self, user_id: str) -> Dict[str, Any]: ...
    def domain_rules(self) -> List[str]: ...
